# config/settings.yaml
database:
  type: oracle
  host: srvvkplanctl.keralty.com
  port: 1521
  service_name: PLANCON
  user: USUDPLANCTL
  password: eYIkp#uVyS#pfX3F4fb1Mi

app:
  log_level: "INFO"
  data_path: "data"

processing:
  # Rutas de archivos
  excel_path: "inputs/Retroactivo EPS _CKI_2025_ Final.xlsx"
  excel_sheet_name: "APLICA RETROACTIVO"
  output: "retroactivo_clinica_salida.csv"

  # Parámetros de la base de datos
  prestador_id: "800149384"
  db_batch_size: 1000
  db_chunk_size: 50000
  base_query: |
    SELECT
        *
    FROM
        tbl_suf_process_2025
    WHERE
            prestador = '{prestador_id}'
        AND procesado = '0'
